Add step to swift workflow to Validate excluded snapshots  (#62)
* wip

* Improve script

* Improve workflow

Co-authored-by: Christopher Fuller <christopher.fuller@gotinder.com>

* Reorder steps

* Lowercase step name

* Improve step

Co-authored-by: Christopher Fuller <christopher.fuller@gotinder.com>

* Improve script

Co-authored-by: Christopher Fuller <christopher.fuller@gotinder.com>

* Remove grep as not needed

* Remove echo statements

* Echo on success

* Improve step script

Co-authored-by: Christopher Fuller <christopher.fuller@gotinder.com>

* Remove success handling

---------

Co-authored-by: Christopher Fuller <christopher.fuller@gotinder.com>

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -18,6 +18,17 @@ jobs:
     steps:
     - name: Checkout source
       uses: actions/checkout@v3
+    - name: Validate excluded snapshots
+      run: |
+        SNAPSHOTS=$(find Tests -type d -name "__Snapshots__" | sort)
+        EXCLUDED=$(swift package dump-package | jq -r '.targets[] | select(.type == "test") | "Tests/" + .name + "/" + .exclude[]' | sort)
+        UNEXCLUDED=$(comm -23 <(echo "$SNAPSHOTS") <(echo "$EXCLUDED"))
+        if test -n "$UNEXCLUDED"
+        then
+            echo "ERROR: Snapshot directories must be excluded from Swift package:" >&2
+            echo "$UNEXCLUDED" >&2
+            exit 1
+        fi
     - name: Download swiftlint binary
       run: swift package resolve
     - name: Lint
